django-oluwasayoscrumy/oluwasayoscrumy/urls.py
from django.urls import path, include
from .views import index, move_goal, home, add_goal

app_name = "oluwasayoscrumy"


urlpatterns = [
    path("", index, name="index"),
    path("movegoal/<int:goal_id>", move_goal, name="move-goal"),
    path("addgoal/", add_goal, name="add-goal"),
    path("accounts/", include("django.contrib.auth.urls") ),
    path("home/", home, name="home"),
]

myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("oluwasayoscrumy/", include("oluwasayoscrumy.urls", namespace="oluwasayoscrumy")),
    path("websocket/", include("websocket.urls", namespace="websocket")),
]

oluwasayoscrumy/urls.py
from django.urls import path, include
from .views import index, move_goal, home, add_goal, SuccessView

app_name = "oluwasayoscrumy"


urlpatterns = [
    path("", index, name="index"),
    path("movegoal/<int:goal_id>", move_goal, name="move-goal"),
    path("addgoal/", add_goal, name="add-goal"),
    path("accounts/", include("django.contrib.auth.urls"), name="login"),
    path("home/", home, name="home"),
    path("create_success/", SuccessView.as_view(), name="created")
]

django-oluwasayoscrumy/oluwasayoscrumy/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class GoalStatus(models.Model):
    status_name = models.CharField(max_length=50)

    def __str__(self):
        return self.status_name


class ScrumyGoal(models.Model):
    goal_id = models.IntegerField(unique=True)
    goal_name = models.CharField(max_length=50)
    created_by = models.CharField(max_length=50)
    moved_by = models.CharField(max_length=50)
    owner = models.CharField(max_length=50)
    goal_status = models.ForeignKey(GoalStatus, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name="goals")

    def __str__(self):
        return self.goal_name


class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=50)
    created_by = models.CharField(max_length=50)
    moved_from = models.CharField(max_length=50)
    moved_to = models.CharField(max_length=50)
    time_of_action = models.DateTimeField()
    goal = models.ForeignKey(ScrumyGoal, on_delete=models.PROTECT)

    def __str__(self):
        return self.created_by

oluwasayoscrumy/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class GoalStatus(models.Model):
    status_name = models.CharField(max_length=50)

    def __str__(self):
        return self.status_name


class ScrumyGoal(models.Model):
    goal_id = models.IntegerField(unique=True)
    goal_name = models.CharField(max_length=50)
    created_by = models.CharField(max_length=50)
    moved_by = models.CharField(max_length=50)
    owner = models.CharField(max_length=50)
    goal_status = models.ForeignKey(GoalStatus, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name="goals")

    def __str__(self):
        return self.goal_name


class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=50)
    created_by = models.CharField(max_length=50)
    moved_from = models.CharField(max_length=50)
    moved_to = models.CharField(max_length=50)
    time_of_action = models.DateTimeField()
    goal = models.ForeignKey(ScrumyGoal, on_delete=models.PROTECT)

    def __str__(self):
        return self.created_by

oluwasayoscrumy/forms.py
from django import forms
from django.contrib.auth import models
from django.forms import fields
from .models import ScrumyGoal
from django.contrib.auth.models import User

class SignUpForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email",  "username", "password"]

class CreateGoalForm(forms.ModelForm):
    class Meta:
        model = ScrumyGoal
        fields = ["goal_name", "user", "goal_status"]

class MoveGoalForm(forms.ModelForm):
    class Meta:
        model = ScrumyGoal
        fields = ["goal_status",]

django-oluwasayoscrumy/oluwasayoscrumy/views.py
import random
from django.http.request import HttpRequest
from django.shortcuts import render
from django.http import HttpResponse
from .models import ScrumyGoal, GoalStatus
from django.contrib.auth.models import User

# Create your views here.


def index(request):
    data = ScrumyGoal.objects.filter(goal_name="Learn Django").first()
    context = {"data": data.goal_name}
    return render(request, "oluwasayoscrumy/index.html", context)


def move_goal(request, goal_id):
    try:
        data = ScrumyGoal.objects.get(goal_id=goal_id).goal_name
    except ScrumyGoal.DoesNotExist:
        data = "Goal with ID {} does not exist".format(goal_id)
        context = { "error": data }
        return render(request, 'oluwasayoscrumy/exception.html', context)
    except:
        data = "Invalid ID"
    return HttpResponse(f"<h1>Goal: {data}</h1>")


def add_goal(request):
    goal_id = random.randrange(1000, 9999)
    while ScrumyGoal.objects.filter(goal_id=goal_id):
        goal_id = random.randrange(1000, 9999)
    usernames = ["louis", "oluwasayo"]
    user = User.objects.get(username=random.choice(usernames))
    goal_status = GoalStatus.objects.get(status_name="Weekly Goal")
    goals = ["Learn Django", "Keep Learning Django"]
    ScrumyGoal.objects.create(
        goal_name=random.choice(goals),
        goal_id=goal_id,
        created_by="Louis",
        moved_by="Louis",
        goal_status=goal_status,
        user=user,
    )
    return HttpResponse("Created Goal")


def home(request):
    response = []
    users = User.objects.all()
    for user in users:
        response.append({
            'user': user, 
            'weekly_goals': user.goals.filter(goal_status__status_name="Weekly Goal"),
            'daily_goals': user.goals.filter(goal_status__status_name="Daily Goal"),
            'verify_goals': user.goals.filter(goal_status__status_name="Verify Goal"),
            'done_goals': user.goals.filter(goal_status__status_name="Done Goal"),
            })

    context = {
        "users": response
    }
   
    return render(request, 'oluwasayoscrumy/home.html', context)

oluwasayoscrumy/views.py
import random
from django.http.request import HttpRequest
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponse
from .models import ScrumyGoal, GoalStatus
from django.contrib.auth.models import User, Group
from .forms import MoveGoalForm, SignUpForm, CreateGoalForm
from django.urls import reverse
from django.views import generic

# Create your views here.


def index(request):
    form = SignUpForm()
    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()
            group = Group.objects.get(name="Developer")
            group.user_set.add(user)
            group.save()

            return HttpResponseRedirect(reverse("oluwasayoscrumy:created"))

    else:
        form = SignUpForm()
    
    context = {"data": "Sign Up", "form": form, "current_user": request.user}
    return render(request, "oluwasayoscrumy/index.html", context)


def move_goal(request, goal_id):
    if request.method == "POST":
        goal = ScrumyGoal.objects.get(goal_id=goal_id)
        form = MoveGoalForm(request.POST, instance=goal)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("oluwasayoscrumy:home"))
    else:
        try:
            goal = ScrumyGoal.objects.get(goal_id=goal_id)
            form = MoveGoalForm(instance=goal)
        except ScrumyGoal.DoesNotExist:
            data = "Goal with ID {} does not exist".format(goal_id)
            return render(request, 'oluwasayoscrumy/exception.html', {"error": data })
    return render(request, "oluwasayoscrumy/move-goal.html", { "form": form, "goal_id": goal_id, "current_user": request.user})


def add_goal(request):
    if request.method == "POST":
        
        form = CreateGoalForm(request.POST)

        if form.is_valid():
            goal = form.save(commit=False)
            goal_id = random.randrange(1000, 9999)
            goal_status = GoalStatus.objects.get(status_name=random.choice(["Weekly Goal", "Daily Goal", "Done Goal", "Verify Goal" ]))
            while ScrumyGoal.objects.filter(goal_id=goal_id):
                goal_id = random.randrange(1000, 9999)
            goal.goal_id = goal_id
            goal.goal_status = goal_status
            goal.save()
            form.save_m2m()

            return HttpResponseRedirect(reverse("oluwasayoscrumy:add-goal"))
    else:
        form = CreateGoalForm()

    context = {"form": form, "current_user": request.user}
    return render(request, 'oluwasayoscrumy/add-goal.html', context=context)


def home(request):
    print(dir(request.user))
    print(request.user.groups)
    users = User.objects.all()
    context = {
        "users": users,
        "current_user": request.user
    }
    return render(request, 'oluwasayoscrumy/home.html', context)


def success(request):
    return render(request, "oluwasayoscrumy/create-success.html")

class SuccessView(generic.TemplateView):

    template_name = 'oluwasayoscrumy/create-success.html'

oluwasayoscrumy/templates/oluwasayoscrumy/add-goal.html
{% extends 'oluwasayoscrumy/base.html' %} 

{% block body %}
<main class="heading">
    <form method="POST">
      <h1>Add a goal</h1>
      {% csrf_token %} 
      {{ form.as_p }} 
      {% if form.errors %}
        <h1>Error Occured</h1>
      {% endif %}
      <button type="submit">Submit</button>
    </form>
</main>
{% endblock body %}

oluwasayoscrumy/templates/oluwasayoscrumy/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      .heading {
        text-align: center;
      }
      table {
        width: 40vw;
        height: 100vh;
        overflow-y: scroll;
      }

      table,
      th,
      td {
        border: 1px solid black;
        border-collapse: collapse;
      }

      div {
        height: 85vh;
        overflow-y: scroll;
        border: 1px solid cornflowerblue;
      }
    </style>
  </head>
  <body>
    {% if current_user %}
        <h2>Username: <i>{{ current_user }}</i></h2>
    {% endif %} 
    {% block body %} 

    {% endblock body %}
  </body>
</html>

oluwasayoscrumy/templates/oluwasayoscrumy/create-success.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      .heading {
        text-align: center;
      }

      .form-input {
        margin-bottom: 10px;
      }
    </style>
  </head>
  <body>
    <div class="heading">
      <h1>Your account has been created successfully</h1>
      <h2><a href="{% url 'oluwasayoscrumy:login'%}">Login</a></h2>
    </div>
  </body>
</html>

oluwasayoscrumy/templates/oluwasayoscrumy/exception.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      .heading {
        text-align: center;
      }
    </style>
  </head>
  <body>
      {% if error %}
    <h1>Error 404</h1>
    <h3>{{ error }}</h3>
    {% endif %}
  </body>
</html>

oluwasayoscrumy/templates/oluwasayoscrumy/home.html
{% extends 'oluwasayoscrumy/base.html' %}

{% block body %}
<h1 class="heading">Goals Table</h1>
<h3><a href="{% url 'oluwasayoscrumy:add-goal' %}">Add Goal</a></h3>
<div>
  <table class="heading">
    <thead>
      <tr>
        <th>User</th>
        <th>Weekly Goals</th>
        <th>Daily Goals</th>
        <th>Verify Goals</th>
        <th>Done Goals</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
      <tr>
        <td>{{ user }}</td>
        <td>
          {% for goal in user.goals.all %} 
          {% ifequal goal.goal_status.status_name "Weekly Goal" %}
          <p>
            <b>{{ goal.goal_id }}</b> -
            <a href="{% url 'oluwasayoscrumy:move-goal' goal.goal_id %}"
              >{{ goal.goal_name }}</a
            >
          </p>
          {% endifequal %} 
          {% endfor %}
        </td>
        <td>
          {% for goal in user.goals.all %} 
          {% ifequal goal.goal_status.status_name "Daily Goal" %}
          <p>
            <b>{{ goal.goal_id }}</b> -
            <a href="{% url 'oluwasayoscrumy:move-goal' goal.goal_id %}"
              >{{ goal.goal_name }}</a
            >
          </p>
          {% endifequal %} 
          {% endfor %}
        </td>
        <td>
          {% for goal in user.goals.all %} 
          {% ifequal goal.goal_status.status_name "Verify Goal" %}
          <p>
            <b>{{ goal.goal_id }}</b> -
            <a href="{% url 'oluwasayoscrumy:move-goal' goal.goal_id %}"
              >{{ goal.goal_name }}</a
            >
          </p>
          {% endifequal %} 
          {% endfor %}
        </td>
        <td>
          {% for goal in user.goals.all %} 
          {% ifequal goal.goal_status.status_name "Done Goal" %}
          <p>
            <b>{{ goal.goal_id }}</b> -
            <a href="{% url 'oluwasayoscrumy:move-goal' goal.goal_id  %}"
              >{{ goal.goal_name }}</a
            >
          </p>
          {% endifequal %} 
          {% endfor %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock body %}

oluwasayoscrumy/templates/oluwasayoscrumy/index.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      .heading {
        text-align: center;
      }
    </style>
  </head>
  <body>
    <h1 class="heading">{{ data }}</h1>
    {% if goal %}
    <h3>Goal: <span>{{ goal }}</span></h3>
    {% endif %}
    <form method="POST">
      {% csrf_token %}
        {{ form.as_p }}
      <button type="submit">Submit</button>
    </form>
  </body>
</html>

oluwasayoscrumy/templates/oluwasayoscrumy/move-goal.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      .heading {
        text-align: center;
      }
    </style>
  </head>
  <body class="heading">
    <form method="POST">
        <h1>Move goal</h1>
      {% csrf_token %}
      {{ form.as_p }}

      {% if form.errors %}
          <h1>Error Occured</h1>
      {% endif %}
      <button type="submit">Submit</button>
    </form>
  </body>
</html>